# Generated by Django 6.0 on 2025-12-12 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='ID from the Next.js application', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'api_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['external_id'], name='api_categor_externa_69709a_idx'), models.Index(fields=['name'], name='api_categor_name_ba8d0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='ID from the Next.js application', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['external_id'], name='api_departm_externa_a7f4c6_idx'), models.Index(fields=['name'], name='api_departm_name_5e40a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='ID from the Next.js application', max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_profiles',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['external_id'], name='api_profile_externa_50f78a_idx'), models.Index(fields=['full_name'], name='api_profile_full_na_f49c11_idx'), models.Index(fields=['department'], name='api_profile_departm_8a6eba_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_external_id', models.CharField(db_index=True, help_text='Asset ID from the Next.js application', max_length=255, unique=True)),
                ('asset_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('asset_created_by', models.CharField(blank=True, help_text='User ID who created the asset in Next.js app', max_length=255, null=True)),
                ('asset_created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Warranty Registered'), ('expired', 'Warranty Expired'), ('claimed', 'Warranty Claimed'), ('void', 'Void')], db_index=True, default='registered', max_length=20)),
                ('registered_by_name', models.CharField(blank=True, help_text='Name of user who registered (from Next.js app)', max_length=255, null=True)),
                ('registered_by_external_id', models.CharField(blank=True, db_index=True, help_text='User ID from Next.js app who registered', max_length=255, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warranty_start_date', models.DateField(blank=True, help_text='Warranty start date (defaults to registration date)', null=True)),
                ('warranty_end_date', models.DateField(blank=True, help_text='Warranty expiration date', null=True)),
                ('warranty_duration_months', models.PositiveIntegerField(default=12, help_text='Warranty duration in months')),
                ('notes', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_by', models.ForeignKey(blank=True, help_text='Django user who registered the warranty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warranty Registration',
                'verbose_name_plural': 'Warranty Registrations',
                'db_table': 'api_warranty_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('status_change', 'Status Changed'), ('delete', 'Deleted')], max_length=20)),
                ('performed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.warrantyregistration')),
            ],
            options={
                'db_table': 'api_warranty_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['status', 'registered_at'], name='api_warrant_status_f97759_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['department', 'status'], name='api_warrant_departm_c33aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['category', 'status'], name='api_warrant_categor_56cd81_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['registered_by_external_id', 'registered_at'], name='api_warrant_registe_5952c0_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['asset_external_id'], name='api_warrant_asset_e_c415d9_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['asset_name'], name='api_warrant_asset_n_28532c_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['registered_at'], name='api_warrant_registe_fa97a5_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyregistration',
            index=models.Index(fields=['warranty_end_date'], name='api_warrant_warrant_e2be8a_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyauditlog',
            index=models.Index(fields=['warranty', 'timestamp'], name='api_warrant_warrant_47e700_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='api_warrant_action_e84f82_idx'),
        ),
    ]
